spring:
  application:
    name: otel-datadog
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

server:
  port: 8080

workflow:
  job-manager-url: ${JOB_MANAGER_URL:http://job-manager:8081}
  pricer-url: ${PRICER_URL:http://pricer:8083}

azure:
  servicebus:
    connection-string: ${SERVICEBUS_CONNECTION_STRING:Endpoint=sb://servicebus-emulator;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;}
    topic-job-processed: ${JOB_PROCESSED_TOPIC:job-processed}
    subscription-job-processed: ${JOB_PROCESSED_SUBSCRIPTION:java-sub}

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus

logging:
  level:
    root: INFO
    com.example.demo: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
